### ISSUE TITLE
Make an <link> element in the WhereBy.Design

### ISSUE THREAD

**Issue by shar0906** [wherebyus/general-tasks#662] opened 2019-01-17 16:27 UTC
Per Schofield, RE: issue-659

Design thingies should be sourced in WhereBy Design rather than tweaks made in Frodo. We should

1. Make an <link> element in the design system
2. Design good links for all ze brands
3. Apply the resulting CSS, etc., to our various apps.

The problems with all of our existing links is that few of them pass accessibility contrast things. So any new colors and stuff we choose need to have a good color contrast ratio. I'm sure the bridgeliner brown is fine, but that's not true for, say, TNT green.

The real kicker is this: our design is going to become more Newsletter like, right now the links in the newsletter are the same font color as the text but underlined:
https://wherebyus.github.io/whereby.design/#/Templates/Newsletter

This is regardless of the brand but would apply to everything, rather than figure out Bridgeliner-specific link colors.

**Comment by ErnieAtLYD** [comment] 2019-03-01 19:56
Related to #784

**Comment by ErnieAtLYD** [comment] 2019-03-05 16:09
Dupe of #784

**Closed by ErnieAtLYD** 2019-03-05 16:09 UTC
Labels: Type: Enhancement
