### ISSUE TITLE
mobile: broken line spacing on login module on mobile

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#888] opened 2019-03-04 05:48 UTC
## Reproduction Steps
Go to thenewtropic.com/join on an iPhone X 

## Expected Results
The login component should have legible line spacing

## Actual Results
The line spacing of “your account’s how you access your perks” is smushed together and hard to read, looks broken.

![image.png](https://images.zenhubusercontent.com/5b3b8639fc589b1d091c443c/285b0222-7589-48ad-87be-1b6dd22197ab)

### Additional information:
 - BTID-441
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recmKzht0AJhfqrUA) - (may include image attachments)

### Submitted by
Name: Christopher Sopher 
Email: chris@whereby.us
Slack ID: cksopher

**Comment by ErnieAtLYD** [comment] 2019-03-04 16:41
Closed as dupe of #877

**Closed by ErnieAtLYD** 2019-03-04 16:41 UTC
Labels: BTID, Severity: Medium, Type: Bug, WBD: Login, WBU Bug AirTable
