### ISSUE TITLE
Newsletter h4 headings

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#926] opened 2019-03-11 14:38 UTC
## Reproduction Steps
I've looked at these on desktop (Chrome, gmail) and mobile (iPhone 7) and it's the same thing -- almost all the headers look different. Some are left in all caps. Others are stripped of all caps. And manual h4 tags (i.e. the outro and member block) don't look like headings at all. See attached screenshots.

## Actual Results
see attached screenshots

### Additional information:
 - BTID-455
 - [Link to Airtable](https://airtable.com/tblWM0skJCYIBSL6c/viwVfilkH4LzzRsKs/recIWVKjyun6TVWgR) - (may include image attachments)

### Submitted by
Name: 
Email: 
Slack ID:

**Comment by ErnieAtLYD** [comment] 2019-03-12 17:38
Duplicate of #920 so I'm closing

**Closed by ErnieAtLYD** 2019-03-12 17:38 UTC
Labels: BTID, WBU Bug AirTable
