### ISSUE TITLE
make the links in the newsletter both colored and underlined to bring back color without compromising accessibility

### ISSUE THREAD

**Issue by wbuacct** [wherebyus/general-tasks#865] opened 2019-02-27 16:43 UTC
### Can we make the links in the newsletter both colored and underlined to bring back color without compromising accessibility?

Suggested by moniguzman

**Comment by ErnieAtLYD** [comment] 2019-03-01 20:28
Related to #784

**Comment by ErnieAtLYD** [comment] 2019-03-05 16:10
Dupe of #784

**Closed by ErnieAtLYD** 2019-03-05 16:10 UTC
Labels: Product: Newsletters, Type: Idea
